name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x' # 確保與你的專案版本一致

      - name: Publish .NET Project
        run: dotnet publish -c Release -o release

      # 建立 CNAME 檔案是為了告訴 GitHub Pages：這個專案要對應到你的網域
      - name: Add CNAME file
        run: echo "me.dev-chi.com" > release/wwwroot/CNAME

      # 處理 SPA (Blazor) 重新整理後 404 的問題
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # 告訴 GitHub Pages 不要用 Jekyll 處理靜態檔案
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit files to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages